<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.17">
  <POU Name="F_SetHeaderInfo" Id="{c0cb69a6-d7df-4110-b29a-d4f544266ffe}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_SetHeaderInfo : BOOL
VAR_IN_OUT
	Msg	:ANY;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>